import type { ThemeV2 } from "./theme-config";
import { defaultThemeV2 } from "./theme-config";

export type Template = {
	id: string;
	name: string;
	description: string;
	config: ThemeV2;
};

const t = (patch: Partial<ThemeV2>): ThemeV2 => ({
	...defaultThemeV2,
	...patch,
});

export const templates: Template[] = [
	{
		id: "minimal",
		name: "Minimal",
		description: "Clean, whitespace-forward, monochrome accents.",
		config: t({
			bg: "#fafafa",
			fg: "#0a0a0a",
			muted: "#71717a",
			surface: "#ffffff",
			border: "#e4e4e7",
			accent: "#0a0a0a",
			accent2: "#525252",
			bgStyle: "solid",
			headingFont: "inter",
			bodyFont: "inter",
			radius: 6,
			cardPadding: 18,
			shadow: "none",
			buttonStyle: "outline",
			hover: "lift",
		}),
	},
	{
		id: "glass",
		name: "Glassmorphism",
		description: "Frosted layers over a colorful mesh.",
		config: t({
			bg: "#0f0a1f",
			fg: "#fafafa",
			muted: "#a5a1c9",
			surface: "#1a1338",
			border: "#2d2560",
			accent: "#a78bfa",
			accent2: "#22d3ee",
			bgStyle: "mesh",
			radius: 20,
			cardPadding: 20,
			shadow: "lg",
			glass: true,
			buttonStyle: "glass",
			hover: "glow",
			headingFont: "space-grotesk",
			bodyFont: "inter",
		}),
	},
	{
		id: "github",
		name: "GitHub",
		description: "Dark, familiar, code-first.",
		config: t({
			bg: "#0d1117",
			fg: "#e6edf3",
			muted: "#7d8590",
			surface: "#161b22",
			border: "#30363d",
			accent: "#2f81f7",
			accent2: "#3fb950",
			bgStyle: "solid",
			radius: 6,
			cardPadding: 16,
			shadow: "sm",
			buttonStyle: "outline",
			hover: "lift",
			headingFont: "inter",
			bodyFont: "inter",
			monoFont: "jetbrains",
		}),
	},
	{
		id: "vscode",
		name: "VSCode",
		description: "Editor-inspired with syntax accents.",
		config: t({
			bg: "#1e1e1e",
			fg: "#d4d4d4",
			muted: "#858585",
			surface: "#252526",
			border: "#333333",
			accent: "#569cd6",
			accent2: "#c586c0",
			bgStyle: "solid",
			radius: 4,
			cardPadding: 14,
			shadow: "none",
			buttonStyle: "solid",
			hover: "none",
			headingFont: "jetbrains",
			bodyFont: "jetbrains",
			monoFont: "jetbrains",
			letterSpacing: 0,
		}),
	},
	{
		id: "cyberpunk",
		name: "Cyberpunk",
		description: "Magenta + cyan on deep purple with glow.",
		config: t({
			bg: "#0a0014",
			fg: "#f0f0ff",
			muted: "#8b7ec7",
			surface: "#16082b",
			border: "#3b1770",
			accent: "#ff2bd6",
			accent2: "#00e5ff",
			bgStyle: "gradient",
			bgAngle: 135,
			radius: 2,
			cardPadding: 18,
			shadow: "glow",
			buttonStyle: "gradient",
			hover: "glow",
			headingFont: "space-grotesk",
			bodyFont: "inter",
			monoFont: "jetbrains",
			letterSpacing: 2,
		}),
	},
	{
		id: "retro",
		name: "Retro",
		description: "80s pastels on cream with rounded chunky cards.",
		config: t({
			bg: "#fdf6e3",
			fg: "#3b2f2f",
			muted: "#8a7a5b",
			surface: "#fffaf0",
			border: "#e6c98a",
			accent: "#e94f74",
			accent2: "#f7b32b",
			bgStyle: "dots",
			radius: 20,
			cardPadding: 20,
			shadow: "md",
			buttonStyle: "solid",
			hover: "shift",
			buttonBorder: 2,
			headingFont: "fraunces",
			bodyFont: "manrope",
		}),
	},
	{
		id: "terminal",
		name: "Terminal",
		description: "Monospace green-on-black.",
		config: t({
			bg: "#000000",
			fg: "#33ff66",
			muted: "#1f7a3a",
			surface: "#050505",
			border: "#1a4d2a",
			accent: "#33ff66",
			accent2: "#a3ff3e",
			bgStyle: "grid",
			radius: 0,
			cardPadding: 14,
			shadow: "none",
			buttonStyle: "outline",
			hover: "none",
			headingFont: "jetbrains",
			bodyFont: "jetbrains",
			monoFont: "jetbrains",
			letterSpacing: 1,
		}),
	},
	{
		id: "neon",
		name: "Neon",
		description: "Ultra-dark base, saturated neon accents.",
		config: t({
			bg: "#050510",
			fg: "#f5f5ff",
			muted: "#7a7aa0",
			surface: "#0d0d1c",
			border: "#1f1f3d",
			accent: "#00ffa3",
			accent2: "#ff0080",
			bgStyle: "radial",
			radius: 14,
			cardPadding: 18,
			shadow: "glow",
			buttonStyle: "gradient",
			hover: "glow",
			headingFont: "space-grotesk",
			bodyFont: "inter",
		}),
	},
	{
		id: "dark",
		name: "Dark",
		description: "The default. Slate + violet.",
		config: defaultThemeV2,
	},
	{
		id: "light",
		name: "Light",
		description: "Bright, neutral, professional.",
		config: t({
			bg: "#ffffff",
			fg: "#111827",
			muted: "#6b7280",
			surface: "#f9fafb",
			border: "#e5e7eb",
			accent: "#4f46e5",
			accent2: "#0891b2",
			bgStyle: "solid",
			radius: 10,
			cardPadding: 16,
			shadow: "sm",
			buttonStyle: "solid",
			hover: "lift",
			headingFont: "inter",
			bodyFont: "inter",
		}),
	},
];

export function templateById(id: string | null | undefined): Template | null {
	if (!id) return null;
	return templates.find((tpl) => tpl.id === id) ?? null;
}
