import type { ThemeV2 } from "./theme-config";
import { defaultThemeV2 } from "./theme-config";

export type Template = {
	id: string;
	name: string;
	description: string;
	config: ThemeV2;
};

const t = (patch: Partial<ThemeV2>): ThemeV2 => ({
	...defaultThemeV2,
	...patch,
});

export const templates: Template[] = [
	{
		id: "terminal",
		name: "Terminal",
		description: "Monospace green-on-black. Pure command-line energy.",
		config: t({
			bg: "#000000",
			fg: "#33ff66",
			muted: "#1f7a3a",
			surface: "#050505",
			border: "#1a4d2a",
			accent: "#33ff66",
			accent2: "#a3ff3e",
			bgStyle: "grid",
			radius: 0,
			cardPadding: 14,
			shadow: "none",
			buttonStyle: "outline",
			hover: "none",
			headingFont: "jetbrains",
			bodyFont: "jetbrains",
			monoFont: "jetbrains",
			letterSpacing: 1,
		}),
	},

	{
		id: "retro",
		name: "Retro",
		description: "80s-inspired pastels, warm paper and chunky controls.",
		config: t({
			bg: "#fdf6e3",
			fg: "#3b2f2f",
			muted: "#8a7a5b",
			surface: "#fffaf0",
			border: "#e6c98a",
			accent: "#e94f74",
			accent2: "#f7b32b",
			bgStyle: "dots",
			radius: 20,
			cardPadding: 20,
			shadow: "md",
			buttonStyle: "solid",
			hover: "shift",
			buttonBorder: 2,
			headingFont: "fraunces",
			bodyFont: "manrope",
			monoFont: "ibm-plex-mono",
		}),
	},
	{
		id: "art-deco",
		name: "Art Deco",
		description: "Geometric luxury with deep midnight tones and warm gold.",
		config: t({
			bg: "#17131a",
			fg: "#f4ead7",
			muted: "#9d8f7b",
			surface: "#211c23",
			border: "#5a4935",
			accent: "#d6a84f",
			accent2: "#f0d58a",
			bgStyle: "solid",
			radius: 2,
			cardPadding: 20,
			shadow: "md",
			buttonStyle: "outline",
			hover: "lift",
			buttonBorder: 1,
			headingFont: "fraunces",
			bodyFont: "instrument-sans",
			monoFont: "geist-mono",
		}),
	},
	{
		id: "tokyo-night",
		name: "Tokyo Night",
		description: "Cool blue-violet darkness inspired by modern code editors.",
		config: t({
			bg: "#1a1b26",
			fg: "#c0caf5",
			muted: "#565f89",
			surface: "#24283b",
			border: "#3b4261",
			accent: "#7aa2f7",
			accent2: "#bb9af7",
			bgStyle: "solid",
			radius: 6,
			cardPadding: 16,
			shadow: "sm",
			buttonStyle: "outline",
			hover: "lift",
			headingFont: "geist",
			bodyFont: "geist",
			monoFont: "geist-mono",
		}),
	},

	{
		id: "catppuccin",
		name: "Catppuccin",
		description: "Soft pastel accents over a deep, cozy developer palette.",
		config: t({
			bg: "#1e1e2e",
			fg: "#cdd6f4",
			muted: "#7f849c",
			surface: "#181825",
			border: "#313244",
			accent: "#cba6f7",
			accent2: "#89b4fa",
			bgStyle: "solid",
			radius: 10,
			cardPadding: 18,
			shadow: "sm",
			buttonStyle: "solid",
			hover: "lift",
			headingFont: "geist",
			bodyFont: "geist",
			monoFont: "geist-mono",
		}),
	},

	{
		id: "editorial",
		name: "Editorial",
		description: "Magazine-inspired typography with quiet, refined structure.",
		config: t({
			bg: "#f4f1eb",
			fg: "#181714",
			muted: "#76716a",
			surface: "#faf8f4",
			border: "#d9d3ca",
			accent: "#9d3326",
			accent2: "#c67c4e",
			bgStyle: "solid",
			radius: 2,
			cardPadding: 20,
			shadow: "none",
			buttonStyle: "outline",
			hover: "lift",
			headingFont: "newsreader",
			bodyFont: "instrument-sans",
			monoFont: "geist-mono",
			letterSpacing: -0.5,
		}),
	},

	{
		id: "y2k",
		name: "Y2K",
		description: "Chrome-like surfaces, electric blue and early-web attitude.",
		config: t({
			bg: "#dce7f5",
			fg: "#172033",
			muted: "#667085",
			surface: "#f5f8ff",
			border: "#b7c7dc",
			accent: "#326bff",
			accent2: "#b65cff",
			bgStyle: "gradient",
			bgAngle: 135,
			radius: 18,
			cardPadding: 18,
			shadow: "lg",
			buttonStyle: "gradient",
			hover: "scale",
			buttonBorder: 1,
			headingFont: "space-grotesk",
			bodyFont: "manrope",
			monoFont: "geist-mono",
		}),
	},

	{
		id: "arcade",
		name: "Arcade",
		description: "Dark arcade atmosphere with bright game-inspired accents.",
		config: t({
			bg: "#111327",
			fg: "#f4f3ff",
			muted: "#777b9e",
			surface: "#191c38",
			border: "#2c315d",
			accent: "#ffcc33",
			accent2: "#ff5ca8",
			bgStyle: "grid",
			radius: 4,
			cardPadding: 16,
			shadow: "glow",
			buttonStyle: "solid",
			hover: "glow",
			buttonBorder: 2,
			headingFont: "space-grotesk",
			bodyFont: "geist",
			monoFont: "geist-mono",
		}),
	},

	{
		id: "paper",
		name: "Paper",
		description:
			"Quiet notebook aesthetic with ink, paper and subtle imperfection.",
		config: t({
			bg: "#eee9df",
			fg: "#29261f",
			muted: "#777065",
			surface: "#f7f3eb",
			border: "#d5cec1",
			accent: "#315c4b",
			accent2: "#9a4f38",
			bgStyle: "dots",
			radius: 3,
			cardPadding: 18,
			shadow: "none",
			buttonStyle: "outline",
			hover: "shift",
			headingFont: "fraunces",
			bodyFont: "instrument-sans",
			monoFont: "ibm-plex-mono",
		}),
	},

	{
		id: "studio",
		name: "Studio",
		description: "Quiet luxury, generous spacing and restrained neutrals.",
		config: t({
			bg: "#f7f7f5",
			fg: "#171717",
			muted: "#737373",
			surface: "#ffffff",
			border: "#dededb",
			accent: "#171717",
			accent2: "#6b6b6b",
			bgStyle: "solid",
			radius: 12,
			cardPadding: 22,
			shadow: "sm",
			buttonStyle: "solid",
			hover: "lift",
			headingFont: "geist",
			bodyFont: "instrument-sans",
			monoFont: "geist-mono",
			letterSpacing: -0.5,
		}),
	},
];

export function templateById(id: string | null | undefined): Template | null {
	if (!id) return null;
	return templates.find((tpl) => tpl.id === id) ?? null;
}
